### ISSUE TITLE
Anh chị cho e hỏi: sao không mở được mục Dịch vụ công giống như ZaUI eGovemment trên Zalo Mini App

### ISSUE THREAD

**Issue by thanhpvtvh** [Zalo-MiniApp/zaui-egovernment#1]
Anh chị cho e hỏi: sao không mở được mục Dịch vụ công giống như ZaUI eGovemment trên Zalo Mini App

**Comment by mister-teddy** [comment]
Chào bạn,
`ZaUI eGovemment` là một Mini App demo cho template cùng tên để các bên tích hợp có thể sử dụng cho mục đích triển khai các Mini App thuộc khối hành chính công một cách nhanh chóng. Còn `Dịch vụ công` là một Mini App đã được triển khai và đang live trên nền tảng. Cả hai đều có thể được mở bình thường.
Các câu hỏi tương tự, bạn vui lòng gửi lên [Zalo Mini App Community](https://mini.zalo.me/community) nhé.
Cảm ơn bạn!
